#!/bin/bash

export QTDIR=/home/sts/Qt5.2.0/5.2.0/gcc
export PATH=$QTDIR/bin:$PATH

qmake superterm.pro -r -spec linux-g++

make -r -w -j8 || exit 1

strip release/superterm

# EOF <stefan@scheler.com>

