#!/bin/bash

export QTDIR=/home/sts/qt/5.10.1/gcc_64
export PATH=$QTDIR/bin:$PATH

qmake superterm.pro -r -spec linux-g++

make -r -w -j8 || exit 1

strip build/release/superterm

# EOF <stefan@scheler.com>

