#!/bin/bash

export QTDIR=~/qt/5.11.2/gcc_64
export PATH=$QTDIR/bin:$PATH

rm -rf build/release

qmake superterm.pro -r -spec linux-g++

make -r -w -j8 || exit 1

strip build/release/superterm

# EOF <stefan@scheler.com>

